// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRWYJ3ZR0Qiqt9Den9y8wAptWlVlaWmlg',
    appId: '1:613657644591:web:8233eb01d4d94b7d9f00da',
    messagingSenderId: '613657644591',
    projectId: 'accuease-5f660',
    authDomain: 'accuease-5f660.firebaseapp.com',
    storageBucket: 'accuease-5f660.appspot.com',
    measurementId: 'G-TLQBPWT7XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZ1xzNUrLbrgichgPvFD2L6qMzxrfzKk',
    appId: '1:613657644591:android:46dd3699d5e972ac9f00da',
    messagingSenderId: '613657644591',
    projectId: 'accuease-5f660',
    storageBucket: 'accuease-5f660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6vJvN881rO6flPd1i6D7hxIgTuU4Ywg',
    appId: '1:613657644591:ios:5e3938dd8d0f82e79f00da',
    messagingSenderId: '613657644591',
    projectId: 'accuease-5f660',
    storageBucket: 'accuease-5f660.appspot.com',
    iosBundleId: 'com.example.accuease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf6vJvN881rO6flPd1i6D7hxIgTuU4Ywg',
    appId: '1:613657644591:ios:5e3938dd8d0f82e79f00da',
    messagingSenderId: '613657644591',
    projectId: 'accuease-5f660',
    storageBucket: 'accuease-5f660.appspot.com',
    iosBundleId: 'com.example.accuease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRWYJ3ZR0Qiqt9Den9y8wAptWlVlaWmlg',
    appId: '1:613657644591:web:2d04488da5cf7c799f00da',
    messagingSenderId: '613657644591',
    projectId: 'accuease-5f660',
    authDomain: 'accuease-5f660.firebaseapp.com',
    storageBucket: 'accuease-5f660.appspot.com',
    measurementId: 'G-0V04HLYYLJ',
  );
}
